CREATE TABLE IF NOT EXISTS USUARIO (
	id INT AUTO_INCREMENT PRIMARY KEY,
	nombre VARCHAR(50) NOT NULL,
	password_hash VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS OPERACION (
	id INT AUTO_INCREMENT PRIMARY KEY,
	usuario_id INT NOT NULL,
	tipo VARCHAR(50) NOT NULL,
	fecha DATE NOT NULL,
	descripcion TEXT, 
	FOREIGN KEY (usuario_id) REFERENCES USUARIO(id) 
);

CREATE TABLE IF NOT EXISTS PREGUNTA (
	id INT AUTO_INCREMENT PRIMARY KEY,
	autor VARCHAR(100) NOT NULL,
	curso VARCHAR(50) NOT NULL,
	grupo VARCHAR(50) NOT NULL,
	modulo VARCHAR(100) NOT NULL,
	ra VARCHAR(50) NOT NULL,
	tema VARCHAR(100) NOT NULL,
	enunciado TEXT NOT NULL,
	fecha_creacion DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS PALABRA_CLAVE (
	id INT AUTO_INCREMENT PRIMARY KEY,
	pregunta_id INT,
	palabra VARCHAR(50) NOT NULL,
	FOREIGN KEY (pregunta_id) REFERENCES PREGUNTA(id)
);

CREATE TABLE IF NOT EXISTS EXAMEN (
	id INT AUTO_INCREMENT PRIMARY KEY,
	fecha DATE,
	usuario_id INT,
	FOREIGN KEY (usuario_id) REFERENCES USUARIO(id)
);

CREATE TABLE IF NOT EXISTS EXAMEN_PREGUNTA (
	examen_id INT,
	pregunta_id INT,
	orden INT,
	FOREIGN KEY (examen_id) REFERENCES EXAMEN(id),
	FOREIGN KEY (pregunta_id) REFERENCES PREGUNTA(id)
);

CREATE TABLE IF NOT EXISTS PREGUNTA_TEST (
	pregunta_id INT,
	opcion1 VARCHAR(100),
	opcion2 VARCHAR(100),
	opcion3 VARCHAR(100),
	opcion4 VARCHAR(100),
	correcta INT,
	CHECK (correcta BETWEEN 0 AND 3),
	FOREIGN KEY (pregunta_id) REFERENCES PREGUNTA(id)
);

CREATE TABLE IF NOT EXISTS PREGUNTA_DESARROLLO (
	pregunta_id INT,
	respuesta_modelo TEXT,
	FOREIGN KEY (pregunta_id) REFERENCES PREGUNTA(id)
);

SHOW tables;